clone: 
  depth: 1
kind: pipeline
name: Etherious Drone

steps:
 - name: Kernel Pipeline
   image: archlinux:base-devel
   environment:
     TOKEN:
       from_secret: BOT_API_KEY
     CHATID:
       from_secret: CHAT_ID
   commands:
      - curl -fsSL "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" | bsdtar -C / -xvf -
      - pacman -Syu --needed --noconfirm wget base-devel xmlto inetutils bc cpio python-sphinx python-sphinx_rtd_theme graphviz imagemagick git python2 python zip tzdata
      - ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
      - bash etherious.sh
